// 20230224114408
// http://localhost:5000/materials
const materials = [
  {
    ID: 37,
    SiteMaterialAlias: 50900,
    Name: 'Water - Batch',
    MaterialClass_ID: 7,
  },
  {
    ID: 38,
    SiteMaterialAlias: 1,
    Name: 'No Material',
    MaterialClass_ID: 15,
  },
  {
    ID: 39,
    SiteMaterialAlias: 50009,
    Name: 'Citric Acid - Bulk',
    MaterialClass_ID: 31,
  },
  {
    ID: 40,
    SiteMaterialAlias: 0,
    Name: 'Not Defined',
    MaterialClass_ID: null,
  },
  {
    ID: 41,
    SiteMaterialAlias: 54807,
    Name: 'Dextrose - Bulk',
    MaterialClass_ID: 30,
  },
  {
    ID: 42,
    SiteMaterialAlias: 7037,
    Name: 'Beverage Base',
    MaterialClass_ID: 27,
  },
  {
    ID: 43,
    SiteMaterialAlias: 93309,
    Name: 'Lemon Lime Flavor',
    MaterialClass_ID: 21,
  },
  {
    ID: 44,
    SiteMaterialAlias: 54701,
    Name: 'Sugar - Bulk',
    MaterialClass_ID: 29,
  },
  {
    ID: 45,
    SiteMaterialAlias: 69438,
    Name: 'Liquid Sucrose 67.5%',
    MaterialClass_ID: 25,
  },
  {
    ID: 46,
    SiteMaterialAlias: 93310,
    Name: 'Orange Flavor',
    MaterialClass_ID: 21,
  },
  {
    ID: 47,
    SiteMaterialAlias: 93504,
    Name: 'Cool Blue Raspberry Flavor',
    MaterialClass_ID: 21,
  },
  {
    ID: 48,
    SiteMaterialAlias: 93321,
    Name: 'Fruit Punch Flavor',
    MaterialClass_ID: 21,
  },
  {
    ID: 49,
    SiteMaterialAlias: 93322,
    Name: 'Glacier Freeze Flavor',
    MaterialClass_ID: 21,
  },
  {
    ID: 50,
    SiteMaterialAlias: 94513,
    Name: 'Starch Cloud',
    MaterialClass_ID: 21,
  },
  {
    ID: 51,
    SiteMaterialAlias: 32582,
    Name: 'Gatorade Frost Glacier Freeze',
    MaterialClass_ID: 22,
  },
  {
    ID: 52,
    SiteMaterialAlias: 33875,
    Name: 'Gatorade Fruit Punch',
    MaterialClass_ID: 22,
  },
  {
    ID: 53,
    SiteMaterialAlias: 32555,
    Name: 'Gatorade Cool Blue',
    MaterialClass_ID: 22,
  },
  {
    ID: 54,
    SiteMaterialAlias: 33876,
    Name: 'Gatorade Orange',
    MaterialClass_ID: 22,
  },
  {
    ID: 55,
    SiteMaterialAlias: 33877,
    Name: 'Gatorade Lemon Lime',
    MaterialClass_ID: 22,
  },
  {
    ID: 56,
    SiteMaterialAlias: 500091,
    Name: 'Citric Acid Dissolution',
    MaterialClass_ID: 24,
  },
  {
    ID: 58,
    SiteMaterialAlias: 9004,
    Name: 'Acid',
    MaterialClass_ID: 11,
  },
  {
    ID: 59,
    SiteMaterialAlias: 9003,
    Name: 'Caustic',
    MaterialClass_ID: 12,
  },
  {
    ID: 60,
    SiteMaterialAlias: 9002,
    Name: 'Reuse Water',
    MaterialClass_ID: 13,
  },
  {
    ID: 61,
    SiteMaterialAlias: 9001,
    Name: 'Fresh Water',
    MaterialClass_ID: 13,
  },
  {
    ID: 62,
    SiteMaterialAlias: 9005,
    Name: 'Kosher Caustic',
    MaterialClass_ID: 12,
  },
  {
    ID: 63,
    SiteMaterialAlias: 548071,
    Name: 'Dextrose Dissolution',
    MaterialClass_ID: 26,
  },
  {
    ID: 64,
    SiteMaterialAlias: 11111,
    Name: 'Tea',
    MaterialClass_ID: 32,
  },
  {
    ID: 65,
    SiteMaterialAlias: null,
    Name: 'Err_MtrlID: 10',
    MaterialClass_ID: null,
  },
  {
    ID: 66,
    SiteMaterialAlias: null,
    Name: 'Err_MtrlID: 1444',
    MaterialClass_ID: null,
  },
  {
    ID: 67,
    SiteMaterialAlias: null,
    Name: 'Err_MtrlID: 1111',
    MaterialClass_ID: null,
  },
  {
    ID: 68,
    SiteMaterialAlias: null,
    Name: 'Err_MtrlID: 3401',
    MaterialClass_ID: null,
  },
  {
    ID: 69,
    SiteMaterialAlias: null,
    Name: 'Err_MtrlID: 3009',
    MaterialClass_ID: null,
  },
  {
    ID: 70,
    SiteMaterialAlias: 548072,
    Name: 'Sucrose Dissolution',
    MaterialClass_ID: 33,
  },
  {
    ID: 71,
    SiteMaterialAlias: null,
    Name: 'Err_MtrlID: 4100',
    MaterialClass_ID: null,
  },
  {
    ID: 72,
    SiteMaterialAlias: 54702,
    Name: 'Sugar - Test',
    MaterialClass_ID: 29,
  },
  {
    ID: 73,
    SiteMaterialAlias: null,
    Name: 'Err_MtrlID: 5116',
    MaterialClass_ID: null,
  },
];
module.exports = {materials}