// 20230224114432
// http://localhost:5000/process-classes
const processClasses = [
  {
    ID: 1,
    Name: 'Cleaning Lines',
    Description: 'Cleaning Lines',
    ProcessGroup_ID: null,
  },
  {
    ID: 2,
    Name: 'CIPT',
    Description: 'CIP Tanks',
    ProcessGroup_ID: 5,
  },
  {
    ID: 3,
    Name: 'LSRB',
    Description: 'Liquid Sugar Receiving Bay',
    ProcessGroup_ID: 1,
  },
  {
    ID: 4,
    Name: 'HCFS',
    Description: 'HCFS',
    ProcessGroup_ID: 2,
  },
  {
    ID: 5,
    Name: 'LSRB_HFCS',
    Description: 'Liquid Sugar Reception Line',
    ProcessGroup_ID: 9,
  },
  {
    ID: 6,
    Name: 'HCFS_BT',
    Description: 'HCFS Transfer Line',
    ProcessGroup_ID: 9,
  },
  {
    ID: 8,
    Name: 'BT',
    Description: 'Batching Tks',
    ProcessGroup_ID: 3,
  },
  {
    ID: 9,
    Name: 'FSBT',
    Description: 'Fruc/Sucr Batch Tks',
    ProcessGroup_ID: 3,
  },
  {
    ID: 10,
    Name: 'WTRL',
    Description: 'Water Lines',
    ProcessGroup_ID: 9,
  },
  {
    ID: 11,
    Name: 'FSBB',
    Description: 'Fruc/Sucr BigBag',
    ProcessGroup_ID: 2,
  },
  {
    ID: 12,
    Name: 'LDBB',
    Description: 'DumpStation BigBag',
    ProcessGroup_ID: 2,
  },
  {
    ID: 13,
    Name: 'FSMX',
    Description: 'Fruc/Sucr Mixing Ln',
    ProcessGroup_ID: 9,
  },
  {
    ID: 15,
    Name: 'FSBT_PREP',
    Description: 'Fruc/Sucr to Prep Ln',
    ProcessGroup_ID: 9,
  },
  {
    ID: 16,
    Name: 'LD',
    Description: 'Dumping Station',
    ProcessGroup_ID: 9,
  },
  {
    ID: 17,
    Name: 'LDMX_PREP',
    Description: 'DumpStation to Prep',
    ProcessGroup_ID: 9,
  },
  {
    ID: 18,
    Name: 'LDMX',
    Description: 'DumpStation Mix',
    ProcessGroup_ID: 9,
  },
  {
    ID: 19,
    Name: 'PREP_BT',
    Description: 'Prep to BatchTks',
    ProcessGroup_ID: 9,
  },
  {
    ID: 20,
    Name: 'BTMX',
    Description: 'BT Mix Line',
    ProcessGroup_ID: 9,
  },
  {
    ID: 21,
    Name: 'PAST',
    Description: 'Pasteruizers B',
    ProcessGroup_ID: 7,
  },
  {
    ID: 22,
    Name: 'ALS',
    Description: 'Alsafe Tanks',
    ProcessGroup_ID: 4,
  },
  {
    ID: 23,
    Name: 'SWG',
    Description: 'Sterile Water Generator',
    ProcessGroup_ID: 9,
  },
  {
    ID: 24,
    Name: 'ALF',
    Description: 'Aseptic Line Flexibility',
    ProcessGroup_ID: 9,
  },
  {
    ID: 25,
    Name: 'FM',
    Description: 'Filler Machines',
    ProcessGroup_ID: 10,
  },
  {
    ID: 26,
    Name: 'CTNW',
    Description: 'Continew',
    ProcessGroup_ID: 9,
  },
  {
    ID: 27,
    Name: 'BT_PAST',
    Description: 'BT to Past Transfer Ln',
    ProcessGroup_ID: 9,
  },
  {
    ID: 29,
    Name: 'UHTD',
    Description: 'UHTD Internal Cleaning',
    ProcessGroup_ID: null,
  },
  {
    ID: 30,
    Name: 'TEA',
    Description: 'GEA Tea Line',
    ProcessGroup_ID: 9,
  },
  {
    ID: 32,
    Name: 'PasteurizerB',
    Description: 'Pasteurizer Internal CIP',
    ProcessGroup_ID: null,
  },
  {
    ID: 33,
    Name: 'SWG_CIP',
    Description: 'Sterile Water Gen CIP',
    ProcessGroup_ID: null,
  },
  {
    ID: 34,
    Name: 'ICE',
    Description: 'Fluidor Ice Crusher',
    ProcessGroup_ID: 9,
  },
];
module.exports = { processClasses };
